// Mocks generated by Mockito 5.4.6 from annotations
// in e_commerce/test/features/authentication/data/repositories/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:e_commerce/config/base_response/base_response.dart' as _i4;
import 'package:e_commerce/features/authentication/data/datasources/auth_local_data_source_contract.dart'
    as _i7;
import 'package:e_commerce/features/authentication/data/datasources/auth_remote_data_source_contract.dart'
    as _i2;
import 'package:e_commerce/features/authentication/data/models/user_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSourceContract extends _i1.Mock
    implements _i2.AuthRemoteDataSourceContract {
  MockAuthRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<String>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i3.Future<_i4.BaseResponse<String>>.value(
              _i5.dummyValue<_i4.BaseResponse<String>>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<String>>);

  @override
  _i3.Future<_i4.BaseResponse<String>> register({
    required String? firstName,
    required String? lastName,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i4.BaseResponse<String>>.value(
              _i5.dummyValue<_i4.BaseResponse<String>>(
                this,
                Invocation.method(#register, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<String>>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.BaseResponse<_i6.UserModel>> getUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, []),
            returnValue: _i3.Future<_i4.BaseResponse<_i6.UserModel>>.value(
              _i5.dummyValue<_i4.BaseResponse<_i6.UserModel>>(
                this,
                Invocation.method(#getUserData, []),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i6.UserModel>>);

  @override
  _i3.Future<_i4.BaseResponse<String>> forgetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [email]),
            returnValue: _i3.Future<_i4.BaseResponse<String>>.value(
              _i5.dummyValue<_i4.BaseResponse<String>>(
                this,
                Invocation.method(#forgetPassword, [email]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<String>>);

  @override
  _i3.Future<_i4.BaseResponse<String>> verifyResetCode(
    String? email,
    String? otp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [email, otp]),
            returnValue: _i3.Future<_i4.BaseResponse<String>>.value(
              _i5.dummyValue<_i4.BaseResponse<String>>(
                this,
                Invocation.method(#verifyResetCode, [email, otp]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<String>>);
}

/// A class which mocks [AuthLocalDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSourceContract extends _i1.Mock
    implements _i7.AuthLocalDataSourceContract {
  MockAuthLocalDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getRefreshToken, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> deleteRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteRefreshToken, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
